# This is a sample GitHub action file that visits a website every hour
name: Visit Website

# This workflow is triggered every hour
on:
  schedule:
    # Runs at the first minute of every hour
    - cron: '0 */25 * * *'
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest
    steps:
      # Use curl command to visit the website
      - name: Visit website
        run: curl https://mycfoo-pushcookie.hf.space/vnc.html && curl https://sokwith-pushcookie.hf.space/vnc.html  && curl https://mycfoo-vnc-0.hf.space/vnc.html  && curl https://sokwith-vnchrome.hf.space/vnc.html

